// Shared configuration + payload helpers for the recipe-service k6 load suite.
//
// These modules are ES-module JavaScript executed by the **k6 binary** (`k6 run ...`) — they are NOT
// part of the vitest suite and must only import from k6's built-in modules (`k6`, `k6/http`,
// `k6/metrics`). All target/credential configuration is read from the environment via k6's `__ENV`.

// Base URL of the recipe-service under test (Nest app / ALB host). Defaults to the local dev port.
export const BASE_URL = (__ENV['RECIPE_API_BASE_URL'] || 'http://localhost:3000').replace(/\/+$/, '');

// A pre-minted Clerk session token (Bearer). Every route except /health is auth-protected, so a real
// run MUST supply this; without it the service answers 401 and the failure-rate threshold trips.
export const TOKEN = __ENV['RECIPE_LOAD_TEST_TOKEN'] || '';

// --- Performance targets (SC-009 / FR-007b-i) ---------------------------------------------------
// p95 <= 500ms for recipe read/list/create and for save even while the S3 archive is queued.
export const SC009_P95_MS = Number(__ENV['RECIPE_SAVE_P95_MS'] || 500);
// Search must return in < 2s.
export const SEARCH_P95_MS = Number(__ENV['RECIPE_SEARCH_P95_MS'] || 2000);

// --- Load shape ---------------------------------------------------------------------------------
// SC-009's headline target is p95 <= 500ms at 10k concurrent. A single k6 runner cannot honestly
// generate 10k VUs, so the peak is env-driven: CI runs a safe smoke value and the true SC-009
// validation supplies a high RECIPE_LOAD_PEAK_VUS from a distributed / k6 Cloud execution.
export const PEAK_VUS = Number(__ENV['RECIPE_LOAD_PEAK_VUS'] || 50);
export const RAMP_UP = __ENV['RECIPE_LOAD_RAMP_UP'] || '30s';
export const HOLD = __ENV['RECIPE_LOAD_HOLD'] || '1m';
export const RAMP_DOWN = __ENV['RECIPE_LOAD_RAMP_DOWN'] || '15s';

// A ramping-vus stage set to the given peak. Shared by every scenario so load shape stays uniform.
export function rampStages(peak) {
    return [
        { duration: RAMP_UP, target: peak },
        { duration: HOLD, target: peak },
        { duration: RAMP_DOWN, target: 0 },
    ];
}

// Read-only headers (Bearer + Accept).
export function authHeaders(extra) {
    const headers = { Accept: 'application/json' };
    if (TOKEN) {
        headers['Authorization'] = `Bearer ${TOKEN}`;
    }
    return Object.assign(headers, extra || {});
}

// Write headers (adds JSON content-type).
export function jsonHeaders() {
    return authHeaders({ 'Content-Type': 'application/json' });
}

// RFC-4122 v4 UUID. Math.random is fine for load-test ingredient ids (not a security context).
export function uuidv4() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
        const r = (Math.random() * 16) | 0;
        const v = c === 'x' ? r : (r & 0x3) | 0x8;
        return v.toString(16);
    });
}

// Seeded baseline ingredient ids (must match tests/global-setup.ts SEED_INGREDIENTS + the k6 CI job's
// seed step). Since T043b, recipe create validates every line's `ingredientId` against the catalog, so a
// random uuid would 400 (UNKNOWN_INGREDIENT) and trip the failure-rate threshold. Load payloads must
// reference ids that actually exist.
export const SEED_INGREDIENT_FLOUR = '00000000-0000-4000-8000-0000000000aa';
export const SEED_INGREDIENT_SUGAR = '00000000-0000-4000-8000-0000000000bb';

// A valid CreateRecipeRequest body (matches specs/001-commise-recipe-app/contracts/api.openapi.yaml).
export function makeRecipePayload(label) {
    return {
        title: `Load Test Recipe ${label}`,
        description: 'Generated by the recipe-service k6 load suite.',
        cuisine: 'italian',
        visibility: 'public',
        ingredients: [
            { ingredientId: SEED_INGREDIENT_FLOUR, name: 'flour', quantity: 2, unit: 'cups' },
            { ingredientId: SEED_INGREDIENT_SUGAR, name: 'sugar', quantity: 1, unit: 'cup' },
        ],
        steps: [
            { instruction: 'Mix the dry ingredients.' },
            { instruction: 'Add the water and knead into a dough.', timerSeconds: 300 },
        ],
        servings: 4,
        prepTimeMinutes: 15,
        cookTimeMinutes: 30,
        totalTimeMinutes: 45,
        tags: ['load-test'],
        dietaryFlags: ['vegetarian'],
    };
}
