#!/usr/bin/env node
/**
 * Fetch the Clerk publishable key from AWS Secrets Manager and write .env.local for the Expo app.
 *
 * Usage:
 *   node scripts/fetch-secrets.mjs [--stage=sandbox|dev|prod]
 *
 * Mirrors the web app's scripts/fetch-secrets.mjs. Requires AWS credentials with SecretsManager read
 * access. The mobile app only needs the PUBLISHABLE key (no secret key — the device never mints tokens
 * with the backend secret); `App.tsx` reads it as EXPO_PUBLIC_IDP_PUBLISHABLE_KEY.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const STAGE = process.argv.find((a) => a.startsWith('--stage='))?.split('=')[1] ?? 'sandbox';
const SECRET_ID = `kitchensink/${STAGE}/identity/keys`;
const ENV_FILE = resolve(import.meta.dirname, '../.env.local');

try {
    const raw = execSync(
        `aws secretsmanager get-secret-value --secret-id ${SECRET_ID} --query SecretString --output text`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
    );
    const { PUBLISHABLE_KEY: publishableKey } = JSON.parse(raw.trim());

    if (!publishableKey) {
        throw new Error('Missing PUBLISHABLE_KEY in secret');
    }

    const lines = [
        '# Auto-generated by scripts/fetch-secrets.mjs',
        '# Do NOT commit this file — .env.local is gitignored',
        '',
        '# Clerk / IDP authentication (sandbox dev instance pk_test). App.tsx reads this at startup.',
        `EXPO_PUBLIC_IDP_PUBLISHABLE_KEY=${publishableKey}`,
        '',
        '# The recipe/identity API origin the typed clients talk to (origin ONLY; they append /api/v1). Point at the',
        '# sandbox recipe host to run the built app against real data; localhost for a local backend.',
        'EXPO_PUBLIC_API_URL=http://localhost:3000',
    ];

    writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
    console.log(`Wrote ${ENV_FILE}`);
} catch (err) {
    console.error('Failed to fetch secrets:', err.message);
    process.exit(1);
}
