#!/usr/bin/env node
/**
 * Fetch the Clerk publishable key from AWS Secrets Manager and write .env.local for the Expo app.
 *
 * Usage:
 *   node scripts/fetch-secrets.mjs [--stage=sandbox|dev|prod]
 *
 * Mirrors the web app's scripts/fetch-secrets.mjs. Requires AWS credentials with SecretsManager read
 * access. The mobile app only needs the PUBLISHABLE key (no secret key — the device never mints tokens
 * with the backend secret); `App.tsx` reads it as EXPO_PUBLIC_IDP_PUBLISHABLE_KEY.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * The stages this script is documented to accept. An allowlist rather than a free string: `STAGE` reaches an
 * AWS call, and the usage note above already promises exactly these three — so anything else is a typo that
 * should fail here, naming the mistake, instead of becoming a "secret not found" further down.
 */
const STAGES = ['sandbox', 'dev', 'prod'];

const STAGE = process.argv.find((a) => a.startsWith('--stage='))?.split('=')[1] ?? 'sandbox';

if (!STAGES.includes(STAGE)) {
    console.error(`Unknown --stage '${STAGE}'. Expected one of: ${STAGES.join(', ')}.`);
    process.exit(1);
}

const SECRET_ID = `kitchensink/${STAGE}/identity/keys`;
const ENV_FILE = resolve(import.meta.dirname, '../.env.local');

try {
    // `execFileSync` with an argument ARRAY, never a shell string: `SECRET_ID` is built from an argv value, so
    // interpolating it into a command line makes the shell an attack surface for whoever runs this. Passing
    // argv straight through spawns `aws` with no shell at all, which also removes the quoting hazard.
    const raw = execFileSync(
        'aws',
        ['secretsmanager', 'get-secret-value', '--secret-id', SECRET_ID, '--query', 'SecretString', '--output', 'text'],
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
    );
    const { PUBLISHABLE_KEY: publishableKey } = JSON.parse(raw.trim());

    if (!publishableKey) {
        throw new Error('Missing PUBLISHABLE_KEY in secret');
    }

    const lines = [
        '# Auto-generated by scripts/fetch-secrets.mjs',
        '# Do NOT commit this file — .env.local is gitignored',
        '',
        '# Clerk / IDP authentication (sandbox dev instance pk_test). App.tsx reads this at startup.',
        `EXPO_PUBLIC_IDP_PUBLISHABLE_KEY=${publishableKey}`,
        '',
        '# The recipe/identity API origin the typed clients talk to (origin ONLY; they append /api/v1). Point at the',
        '# sandbox recipe host to run the built app against real data; localhost for a local backend.',
        'EXPO_PUBLIC_API_URL=http://localhost:3000',
    ];

    writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
    console.log(`Wrote ${ENV_FILE}`);
} catch (err) {
    console.error('Failed to fetch secrets:', err.message);
    process.exit(1);
}
