// @vitest-environment node
/**
 * ⛔ The Maestro job must resolve its Android SDK components BEFORE the expensive build, and must never name
 * a version to do it.
 *
 * ## The failure
 *
 * On 2026-09-04 the heavy tier went red on `a6acefaa` with no Maestro flow having run at all:
 *
 *     "Install NDK (Side by side) 27.1.12297006 v.27.1.12297006" failed.
 *     com.android.builder.sdk.InstallFailedException: Failed to install the following SDK components:
 *           ndk;27.1.12297006
 *     BUILD FAILED in 2m 30s
 *
 * The run before it (`aee76556`) installed the same component from the same runner image and reported
 * `License … accepted` / `Install … complete` / `BUILD SUCCESSFUL in 12m 30s`. Same version, same
 * requirement, nothing in the diff touching Android — a transient download failure.
 *
 * It cost the whole tier, and it reported as **"E2E (mobile — Maestro) failed"**. That is the expensive
 * shape: a toolchain download failing while wearing the name of the thing under test. Nobody reading the
 * job title would guess the APK was never assembled.
 *
 * ## Why the fix is a configuration-phase invocation and not an `sdkmanager` line
 *
 * Gradle downloads these components during CONFIGURATION — the stack trace is explicit that it died
 * *"evaluating root project"* / *"configuring project ':app'"*, not compiling. So a cheap configuration-only
 * task (`:app:tasks`) exercises the identical code path at ~1-2 minutes against ~12 for `assembleRelease`.
 * A transient failure then costs a short retry rather than a twelve-minute build that dies in its second
 * minute, and by the time the real build runs the components are already on disk.
 *
 * ## ⛔ Why no version may be named
 *
 * `ndkVersion` comes from **Expo's own Gradle version catalog** (`expoLibs`, alias `ndkVersion`), not from
 * anything in this repository: `packages/apps/commise/mobile/android/` is generated by `expo prebuild` and
 * is gitignored, and `27.1.12297006` appears in no tracked file. Any literal written into CI would be a
 * second copy of a number this repo does not own, and it would drift silently the next time the Expo SDK
 * moves — the copy-of-a-list failure, one ecosystem over. Letting Gradle ask for what it needs means this
 * step never has to know.
 *
 * ⚠️ HONEST PROVENANCE: this guard was written AFTER the fix, not red-first. It is mutation-proven instead —
 * both assertions were watched to fail against deliberately broken workflow text (see the table below), so
 * it is a live guard rather than a restatement of the diff.
 *
 * | mutation | assertion that dies |
 * |---|---|
 * | drop the `for attempt in` retry loop | `resolves the SDK components in a retried step` |
 * | move the loop after `assembleRelease` | `… BEFORE the expensive build` |
 * | replace `:app:tasks` with a literal `sdkmanager "ndk;27.1.12297006"` | `names no SDK version of its own` |
 *
 * DESIGN PATTERN: Specification module over a pure predicate — the verdict is computed from the step's shell
 * body, so it can be fired at fakes as well as at the real workflow.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { parse } from 'yaml';
import { describe, expect, it } from 'vitest';

const WORKFLOW = fileURLToPath(new URL('../../../../.github/workflows/_ci-heavy.yml', import.meta.url));

/**
 * The shell body with `#` comment lines removed.
 *
 * ⛔ Comments are stripped before any judgement, and that is load-bearing here rather than tidy: the step's
 * own comment QUOTES the failing install message, version and all, because recording the observed failure is
 * what makes the fix reviewable. A check that scanned raw text would read that documentation as the very
 * violation it warns against — and the obvious repair would be to delete the explanation.
 *
 * @param shell - A step's `run:` body.
 * @returns The executable lines only. Pure.
 */
function executableLines(shell: string): string {
    return shell
        .split('\n')
        .filter((line) => !/^\s*#/u.test(line))
        .join('\n');
}

/** The Maestro job's APK build step, located by what it does rather than by its name. */
function apkBuildShell(): string {
    const document = parse(readFileSync(WORKFLOW, 'utf8')) as {
        jobs: Record<string, { steps?: { name?: string; run?: string }[] }>;
    };
    const steps = Object.values(document.jobs).flatMap((job) => job.steps ?? []);
    const build = steps.find((step) => /gradlew[^\n]*assembleRelease/u.test(step.run ?? ''));

    if (build === undefined) {
        throw new Error(
            'no step running `gradlew … assembleRelease` was found in _ci-heavy.yml. If the Android build ' +
                'moved, this guard must move with it rather than pass vacuously.',
        );
    }

    return build.run ?? '';
}

describe('the Maestro job resolves its Android SDK components deliberately', () => {
    it('is not vacuous: the APK build step is found in the real workflow', () => {
        expect(apkBuildShell()).toMatch(/assembleRelease/u);
    });

    it('resolves the SDK components in a RETRIED step, so a transient download is not a red tier', () => {
        const shell = executableLines(apkBuildShell());

        expect(
            shell,
            'the APK build must retry the Android SDK component download. It failed once already, taking ' +
                'the whole heavy tier with it while reporting as a Maestro failure.',
        ).toMatch(/for\s+attempt\s+in/u);
    });

    it('resolves them BEFORE the expensive build, not as part of it', () => {
        const shell = executableLines(apkBuildShell());
        const resolveAt = shell.search(/gradlew[^\n]*:app:tasks/u);
        const buildAt = shell.search(/gradlew[^\n]*assembleRelease/u);

        expect(
            resolveAt,
            'no configuration-only Gradle invocation was found. Without one, the SDK download happens ' +
                'inside `assembleRelease`, where a transient failure costs the full build.',
        ).toBeGreaterThan(-1);
        expect(
            resolveAt,
            'the cheap configuration pass must precede `assembleRelease`; after it, it guards nothing',
        ).toBeLessThan(buildAt);
    });

    it('⛔ names no SDK version of its own — the version belongs to Expo, not to us', () => {
        const shell = executableLines(apkBuildShell());

        // `android/` is generated by `expo prebuild` and gitignored; `ndkVersion` lives in Expo's Gradle
        // version catalog. A literal here would be a copy of a number this repo does not own.
        expect(
            shell.match(/\d+\.\d+\.\d{6,}/gu) ?? [],
            'the build step names an Android SDK component version. Let Gradle ask for what it needs — a ' +
                'literal here drifts the next time the Expo SDK moves, and nothing would notice.',
        ).toEqual([]);
        expect(shell, '`sdkmanager` installs a NAMED component, which is the same copy by another route').not.toMatch(
            /sdkmanager/u,
        );
    });
});
