// @vitest-environment node
/**
 * Guard for the REGENERATION half of `npm run contract:verify` (`scripts/contractGenerate.mjs` +
 * `scripts/contractOwners.mjs`, `docs/CODING_STANDARDS.md` §15.2.5).
 *
 * `contract:verify` is "regenerate, then require the tree to be unchanged". Its regeneration half used to be a
 * bare `turbo run contract:generate --filter='./packages/services/*'`, which has a measured failure mode that is
 * silent in exactly the situation the gate exists for:
 *
 *     $ turbo run contract:generate --filter=@kitchensink/identity-webhooks
 *     WARNING  No tasks were executed as part of this run.
 *     $ echo $?
 *     0
 *
 * So a service that lost or renamed its `contract:generate` script stopped being regenerated with a ZERO exit,
 * the drift check then found no diff for it — nothing had rewritten it — and the run went green over a stale
 * published contract that clients compile against.
 *
 * Two properties make the claim honest, and both are asserted here rather than assumed:
 *
 *  1. **The expected set is derived and cross-checked in both directions**, so it cannot shrink quietly. A break
 *     in the correspondence is a failure, never a smaller expectation.
 *  2. **Every document must have been REWRITTEN by the run.** A zero exit is not evidence; a moved mtime is.
 *
 * ⚠️ This suite deliberately does NOT invoke the real generators. Running them from a test would WRITE into the
 * repository, so a genuinely-drifted checkout would come out of `npm test` silently REPAIRED — the gate reporting
 * success having erased its own evidence. Same reasoning as `contract/__tests__/contract.test.ts`.
 */
import { mkdirSync, mkdtempSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
    discoverContractOwners,
    formatOwnershipReport,
    parseDelegatedWorkspace,
} from '../../../../scripts/contractOwners.mjs';
import { documentsNotRegenerated, filesystemNow } from '../../../../scripts/contractGenerate.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../..');

/** Write a file, creating parent directories. */
function write(root: string, relative: string, contents: string): void {
    const target = path.join(root, relative);

    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, contents);
}

/** Write a `package.json`. */
function writeManifest(root: string, relative: string, manifest: Record<string, unknown>): void {
    write(root, relative, `${JSON.stringify(manifest, null, 4)}\n`);
}

/** Run a body against a throwaway tree, cleaning up afterwards. */
function withTree(body: (root: string) => void): void {
    const root = mkdtempSync(path.join(tmpdir(), 'contract-owners-'));

    try {
        body(root);
    } finally {
        rmSync(root, { recursive: true, force: true });
    }
}

/** A minimal, correct correspondence: one schema package, one service that regenerates it. */
function writeCorrespondence(root: string): void {
    writeManifest(root, 'packages/schemas/food/package.json', {
        name: '@kitchensink/schema-food',
        scripts: { 'contract:generate': 'npm run contract:generate --workspace=@kitchensink/food-service' },
    });
    writeManifest(root, 'packages/services/food-service/package.json', {
        name: '@kitchensink/food-service',
        scripts: { 'contract:generate': 'tsx contract/generate.ts' },
    });
    write(root, 'packages/schemas/food/openapi.yaml', 'openapi: 3.0.3\n');
}

describe('parseDelegatedWorkspace', () => {
    // The correspondence is NOT derivable from the directory names — `packages/schemas/identity` is generated by
    // `@kitchensink/identity-service` in `packages/services/identity` — so it is read out of the script.
    it('reads the service out of a delegating script', () => {
        expect(parseDelegatedWorkspace('npm run contract:generate --workspace=@kitchensink/identity-service')).toBe(
            '@kitchensink/identity-service',
        );
    });

    it('returns undefined for a script that names no workspace, and for no script at all', () => {
        expect(parseDelegatedWorkspace('tsc -p tsconfig.build.json')).toBeUndefined();
        expect(parseDelegatedWorkspace(undefined)).toBeUndefined();
    });
});

describe('discoverContractOwners against the real repository', () => {
    const { owners, problems } = discoverContractOwners(repoRoot);

    // Non-vacuity: every assertion about "the expected set" is worthless if the set is empty.
    it('finds one owner per generated contract package, with no breaks in the correspondence', () => {
        expect(problems).toStrictEqual([]);
        expect(owners.length).toBeGreaterThanOrEqual(3);
    });

    it('names the service that regenerates each document', () => {
        expect(owners.map((owner) => `${owner.documentPath} ← ${owner.serviceName}`)).toStrictEqual([
            'packages/schemas/food/openapi.yaml ← @kitchensink/food-service',
            'packages/schemas/identity/openapi.yaml ← @kitchensink/identity-service',
            'packages/schemas/recipe/openapi.yaml ← @kitchensink/recipe-service',
        ]);
    });
});

describe('discoverContractOwners breaks in the correspondence', () => {
    it('accepts a complete correspondence', () => {
        withTree((root) => {
            writeCorrespondence(root);

            const { owners, problems } = discoverContractOwners(root);

            expect(problems).toStrictEqual([]);
            expect(owners).toStrictEqual([
                {
                    schemaPackageName: '@kitchensink/schema-food',
                    documentPath: 'packages/schemas/food/openapi.yaml',
                    serviceName: '@kitchensink/food-service',
                },
            ]);
        });
    });

    // THE measured case: the script disappears, turbo runs nothing, exits 0, and the drift check finds no diff.
    it('reports a service that no longer declares contract:generate, and drops it from the owners', () => {
        withTree((root) => {
            writeCorrespondence(root);
            writeManifest(root, 'packages/services/food-service/package.json', {
                name: '@kitchensink/food-service',
                scripts: { build: 'nest build' },
            });

            const { owners, problems } = discoverContractOwners(root);

            expect(owners).toStrictEqual([]);
            expect(problems).toHaveLength(1);
            expect(problems[0]).toContain('NEVER regenerated');
        });
    });

    it('reports a schema package that names no generating service', () => {
        withTree((root) => {
            writeCorrespondence(root);
            writeManifest(root, 'packages/schemas/food/package.json', {
                name: '@kitchensink/schema-food',
                scripts: { build: 'tsc' },
            });

            expect(discoverContractOwners(root).problems[0]).toContain("no 'contract:generate' script naming");
        });
    });

    it('reports a schema package delegating to a service that does not exist', () => {
        withTree((root) => {
            writeCorrespondence(root);
            writeManifest(root, 'packages/schemas/food/package.json', {
                name: '@kitchensink/schema-food',
                scripts: { 'contract:generate': 'npm run contract:generate --workspace=@kitchensink/renamed' },
            });

            expect(discoverContractOwners(root).problems[0]).toContain('@kitchensink/renamed');
        });
    });

    // The other direction, which a one-way check would miss: a service generating into a package no gate reads.
    it('reports a service whose generated contract no schema package claims', () => {
        withTree((root) => {
            writeCorrespondence(root);
            writeManifest(root, 'packages/services/notification-service/package.json', {
                name: '@kitchensink/notification-service',
                scripts: { 'contract:generate': 'tsx contract/generate.ts' },
            });

            expect(discoverContractOwners(root).problems[0]).toContain('outside the drift gate');
        });
    });

    it('reports nothing to regenerate as a problem rather than an empty success', () => {
        withTree((root) => {
            writeManifest(root, 'packages/services/food-service/package.json', { name: '@kitchensink/food-service' });

            const { owners, problems } = discoverContractOwners(root);

            expect(owners).toStrictEqual([]);
            expect(problems).toStrictEqual([]);
            // The runner turns an empty expectation into a failure; the discovery just reports it as empty.
            expect(formatOwnershipReport(['No packages/schemas/* package declares a generator at all.'])).toContain(
                'cannot state what it regenerates',
            );
        });
    });
});

describe('documentsNotRegenerated', () => {
    const owners = [
        {
            schemaPackageName: '@kitchensink/schema-food',
            documentPath: 'packages/schemas/food/openapi.yaml',
            serviceName: '@kitchensink/food-service',
        },
    ];

    it('reports a document whose mtime did not move — the "turbo ran nothing" case', () => {
        withTree((root) => {
            write(root, 'packages/schemas/food/openapi.yaml', 'openapi: 3.0.3\n');

            // Age the file so it predates the reference, exactly as a document nobody regenerated would.
            const oneHourAgo = new Date(Date.now() - 3_600_000);

            utimesSync(path.join(root, 'packages/schemas/food/openapi.yaml'), oneHourAgo, oneHourAgo);

            const stale = documentsNotRegenerated(owners, filesystemNow(), root);

            expect(stale).toHaveLength(1);
            expect(stale[0]).toContain('was not rewritten by @kitchensink/food-service');
        });
    });

    it('reports nothing when the document was written after the reference', () => {
        withTree((root) => {
            const reference = filesystemNow();

            write(root, 'packages/schemas/food/openapi.yaml', 'openapi: 3.0.3\n');

            expect(documentsNotRegenerated(owners, reference, root)).toStrictEqual([]);
        });
    });

    it('reports a document the generator never produced', () => {
        withTree((root) => {
            const stale = documentsNotRegenerated(owners, filesystemNow(), root);

            expect(stale).toHaveLength(1);
            expect(stale[0]).toContain('does not exist');
        });
    });
});
