/**
 * @module @commise/ui/icon — the web glyph table: every meaning in the Registry mapped to its `lucide-react` glyph.
 *
 * The only module on web that imports `lucide-react` (`packages/infra/global/__tests__/iconImportBoundary.test.ts`).
 * The package is `sideEffects: false` and its named exports tree-shake, so only the glyphs listed here ship. The native
 * table (`glyphs.native.ts`) must draw the same glyph for every meaning; `__tests__/glyphs.test.tsx` holds the two
 * tables to that.
 *
 * @pattern Registry — a table keyed by the closed `IconName` union, so a meaning without a glyph does not compile
 */
import {
    ArrowUp,
    Bell,
    BookOpen,
    Calendar,
    Camera,
    ChartColumn,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsLeft,
    ClipboardPaste,
    Clock,
    Compass,
    CopyPlus,
    Ellipsis,
    Eye,
    Flame,
    Globe,
    House,
    ImageIcon,
    ImagePlus,
    Info,
    ListPlus,
    Lock,
    LogIn,
    LogOut,
    LayoutGrid,
    List,
    Menu,
    Minus,
    PencilLine,
    Plus,
    RefreshCw,
    RotateCcw,
    Save,
    Search,
    Settings,
    ShoppingCart,
    SlidersHorizontal,
    Star,
    Sun,
    Timer,
    Trash2,
    TriangleAlert,
    User,
    UserPlus,
    UserX,
    Users,
    X,
    type LucideIcon,
} from 'lucide-react';

import type { IconName } from './props.js';

/** The `lucide-react` glyph for each meaning. */
export const GLYPHS: Readonly<Record<IconName, LucideIcon>> = {
    house: House,
    bookOpen: BookOpen,
    compass: Compass,
    plus: Plus,
    clipboardPaste: ClipboardPaste,
    ellipsis: Ellipsis,
    chevronLeft: ChevronLeft,
    x: X,
    search: Search,
    copyPlus: CopyPlus,
    trash: Trash2,
    clock: Clock,
    users: Users,
    flame: Flame,
    star: Star,
    lock: Lock,
    globe: Globe,
    pencilLine: PencilLine,
    timer: Timer,
    sun: Sun,
    check: Check,
    arrowUp: ArrowUp,
    imagePlus: ImagePlus,
    listPlus: ListPlus,
    chevronsLeft: ChevronsLeft,
    slidersHorizontal: SlidersHorizontal,
    rotateCcw: RotateCcw,
    chevronDown: ChevronDown,
    eye: Eye,
    user: User,
    minus: Minus,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    refreshCw: RefreshCw,
    logIn: LogIn,
    logOut: LogOut,
    userPlus: UserPlus,
    userX: UserX,
    save: Save,
    settings: Settings,
    camera: Camera,
    image: ImageIcon,
    triangleAlert: TriangleAlert,
    info: Info,
    calendar: Calendar,
    shoppingCart: ShoppingCart,
    chartColumn: ChartColumn,
    bell: Bell,
    menu: Menu,
    list: List,
    layoutGrid: LayoutGrid,
};
