/**
 * ⛔ The verifier's column register covers EXACTLY the catalog's columns (curated catalog plan U6, KTD-3).
 *
 * Nothing here lists a table or a column. The tables come from food's registry (`FOOD_CATALOG_REGISTRY.catalog`),
 * resolved to their Drizzle declarations by scanning the schema module, and the columns from those declarations.
 * So a migration that adds a catalog column fails this suite until someone decides how the verifier treats it, and
 * a column added as `compared` is owed by construction, which keeps `seedVerifierOwed`'s gate shut until a session
 * compares it.
 *
 * Every disposition but `compared` makes a claim the declaration can refute, and is checked against it:
 *
 * - `generated` if and only if Postgres computes the column (`GENERATED ALWAYS AS`).
 * - `clock` only on a timestamp.
 * - `identity` only on a single-column primary key that references nothing, so a foreign key (whose meaning IS the
 *   row it points at) cannot hide there.
 *
 * Tests may import the seeder (the fence covers `verify/` production code only), and this one must: it reads the
 * schema the verifier is forbidden to import.
 */
import { getTableColumns, getTableName, is } from 'drizzle-orm';
import { getTableConfig, PgTable } from 'drizzle-orm/pg-core';
import { describe, expect, it } from 'vitest';

import { FOOD_CATALOG_REGISTRY } from '../../../../db/schema/catalog.js';
import * as schema from '../../../../db/schema/index.js';
import { COVERED, OWED, VERIFIED_COLUMNS, type ColumnDisposition } from '../verifiedColumns.js';

/** What a column's declaration says about it: the facts a disposition can be refuted by. */
interface DeclaredColumn {
    readonly name: string;
    readonly generated: boolean;
    readonly timestamp: boolean;
    readonly primaryKey: boolean;
    readonly foreignKey: boolean;
}

/** The register's shape, as the predicate reads it. */
type Register = Readonly<Record<string, Readonly<Record<string, ColumnDisposition>>>>;

/**
 * The catalog tables' declared columns, by table. Impure only in that it reads module state.
 *
 * @returns Every catalog table found in the schema module, with its columns.
 */
function declaredCatalog(): ReadonlyMap<string, readonly DeclaredColumn[]> {
    const exported: readonly unknown[] = Object.values(schema);
    const tables = exported.filter(
        (value): value is PgTable => is(value, PgTable) && FOOD_CATALOG_REGISTRY.catalog.has(getTableName(value)),
    );

    return new Map(
        tables.map((table): readonly [string, readonly DeclaredColumn[]] => {
            const references = new Set(
                getTableConfig(table).foreignKeys.flatMap((key) =>
                    key.reference().columns.map((column) => column.name),
                ),
            );

            return [
                getTableName(table),
                Object.values(getTableColumns(table)).map((column): DeclaredColumn => ({
                    name: column.name,
                    generated: column.generated !== undefined,
                    timestamp: column.columnType.startsWith('PgTimestamp'),
                    primaryKey: column.primary,
                    foreignKey: references.has(column.name),
                })),
            ];
        }),
    );
}

/**
 * Why a disposition does not fit a column's declaration, or `undefined` when it does. Pure.
 *
 * @param column - The declaration.
 * @param disposition - The register's disposition.
 */
function misfit(column: DeclaredColumn, disposition: ColumnDisposition): string | undefined {
    if (column.generated !== (disposition === 'generated')) {
        return column.generated ? 'is generated by Postgres' : 'is not a generated column';
    }

    if (disposition === 'clock' && !column.timestamp) {
        return 'is not a timestamp';
    }

    if (disposition === 'identity' && (!column.primaryKey || column.foreignKey)) {
        return column.foreignKey ? 'references another row' : 'is not a single-column primary key';
    }

    return undefined;
}

/**
 * Every way the register differs from the declarations, as sorted messages. Pure.
 *
 * @param declared - The catalog tables' declared columns.
 * @param register - The verifier's register.
 * @returns The problems; empty when the register covers exactly the declarations and each disposition fits.
 */
function registerProblems(declared: ReadonlyMap<string, readonly DeclaredColumn[]>, register: Register): string[] {
    const problems: string[] = [];

    for (const [table, columns] of declared) {
        const entry = register[table];

        if (entry === undefined) {
            problems.push(`${table}: no register entry`);
            continue;
        }

        for (const column of columns) {
            const disposition = entry[column.name];
            const reason = disposition === undefined ? 'has no disposition' : misfit(column, disposition);

            if (reason !== undefined) {
                problems.push(`${table}.${column.name}: ${reason}`);
            }
        }

        const names = new Set(columns.map((column) => column.name));

        for (const name of Object.keys(entry).filter((key) => !names.has(key))) {
            problems.push(`${table}.${name}: not a declared column`);
        }
    }

    for (const table of Object.keys(register).filter((key) => !declared.has(key))) {
        problems.push(`${table}: not a catalog table`);
    }

    return problems.sort();
}

/** One declared column, every fact false unless stated. */
function makeDeclaredColumn(overrides: Partial<DeclaredColumn> & Pick<DeclaredColumn, 'name'>): DeclaredColumn {
    return { generated: false, timestamp: false, primaryKey: false, foreignKey: false, ...overrides };
}

/** A small declared catalog the controls below corrupt one fact at a time. */
const FAKE_DECLARED: ReadonlyMap<string, readonly DeclaredColumn[]> = new Map([
    [
        'thing',
        [
            makeDeclaredColumn({ name: 'id', primaryKey: true }),
            makeDeclaredColumn({ name: 'label' }),
            makeDeclaredColumn({ name: 'created_at', timestamp: true }),
            makeDeclaredColumn({ name: 'label_vector', generated: true }),
        ],
    ],
    ['thing_link', [makeDeclaredColumn({ name: 'thing_id', primaryKey: true, foreignKey: true })]],
]);

/** The register that fits {@link FAKE_DECLARED} exactly. */
const FAKE_REGISTER: Register = {
    thing: { id: 'identity', label: 'compared', created_at: 'clock', label_vector: 'generated' },
    thing_link: { thing_id: 'compared' },
};

describe('the verifier column register', () => {
    it('finds every catalog table in the schema, so the comparison below is not vacuous', () => {
        expect([...declaredCatalog().keys()].sort()).toEqual([...FOOD_CATALOG_REGISTRY.catalog].sort());
    });

    it('⛔ covers exactly the declared catalog columns, each with a disposition its declaration allows', () => {
        expect(registerProblems(declaredCatalog(), VERIFIED_COLUMNS)).toEqual([]);
    });

    it('accepts a register that fits, so the controls below fail for the corruption alone', () => {
        expect(registerProblems(FAKE_DECLARED, FAKE_REGISTER)).toEqual([]);
    });

    it.each<[string, Register, string]>([
        [
            'a declared column missing from the register',
            { ...FAKE_REGISTER, thing: { id: 'identity', created_at: 'clock', label_vector: 'generated' } },
            'thing.label: has no disposition',
        ],
        [
            'a register column no table declares',
            { ...FAKE_REGISTER, thing_link: { thing_id: 'compared', ghost: 'compared' } },
            'thing_link.ghost: not a declared column',
        ],
        [
            'a catalog table missing from the register',
            { thing: FAKE_REGISTER['thing'] ?? {} },
            'thing_link: no register entry',
        ],
        ['a register table outside the catalog', { ...FAKE_REGISTER, extra: {} }, 'extra: not a catalog table'],
        [
            'a value column hidden under identity',
            { ...FAKE_REGISTER, thing: { ...FAKE_REGISTER['thing'], label: 'identity' } },
            'thing.label: is not a single-column primary key',
        ],
        [
            'a foreign-key primary key hidden under identity',
            { ...FAKE_REGISTER, thing_link: { thing_id: 'identity' } },
            'thing_link.thing_id: references another row',
        ],
        [
            'a value column hidden under clock',
            { ...FAKE_REGISTER, thing: { ...FAKE_REGISTER['thing'], label: 'clock' } },
            'thing.label: is not a timestamp',
        ],
        [
            'a value column hidden under generated',
            { ...FAKE_REGISTER, thing: { ...FAKE_REGISTER['thing'], label: 'generated' } },
            'thing.label: is not a generated column',
        ],
        [
            'a generated column claimed as compared',
            { ...FAKE_REGISTER, thing: { ...FAKE_REGISTER['thing'], label_vector: 'compared' } },
            'thing.label_vector: is generated by Postgres',
        ],
    ])('⛔ reports %s', (_case, register, problem) => {
        expect(registerProblems(FAKE_DECLARED, register)).toEqual([problem]);
    });
});

describe('what the verifier still owes', () => {
    /** Every compared column, as `table.column`. */
    const compared = Object.entries(VERIFIED_COLUMNS).flatMap(([table, columns]) =>
        Object.entries(columns)
            .filter(([, disposition]) => disposition === 'compared')
            .map(([column]) => `${table}.${column}`),
    );

    it('owes every compared column no session has covered, and nothing else', () => {
        expect([...OWED].sort()).toEqual(
            compared.filter((column) => !COVERED.some((covered) => covered === column)).sort(),
        );
    });

    it('owes nothing: every compared column is covered, so the seed gate is open', () => {
        expect(OWED).toEqual([]);
    });

    it('covers each column at most once', () => {
        expect(new Set(COVERED).size).toBe(COVERED.length);
    });

    it('owes the ownership column nothing: Postgres derives it, and the verifier never reads it (KTD-3)', () => {
        expect(VERIFIED_COLUMNS.food_item.seed_owned).toBe('generated');
    });
});
