/**
 * THE PUBLISHED-CONTRACT FINGERPRINT — `packages/schemas/<service>/contract.schema.json`.
 *
 * This module projects every zod schema a schema package exports into JSON Schema and serializes the result
 * deterministically. The file it produces is committed beside `openapi.yaml` and regenerated by the same run,
 * so CI's existing regenerate-and-diff gate (`npm run contract:verify`) covers it with no new job.
 *
 * ── ⚠️ WHAT THIS IS NOT: it is a COMPARISON FINGERPRINT, not a CODEGEN INPUT ──
 *
 * ADR-0014 §1 rejects deriving TYPES through JSON Schema, and rejects it for good reasons that have not
 * changed: JSON Schema cannot express `readonly`, branded types or template literals, and a discriminated
 * union flattens without explicit handling — so generating types from it would degrade the strong gate
 * (`typecheck`) in order to serve a weak artifact.
 *
 * **This document generates nothing.** No type, no zod, no client, no server. Nothing in this repository
 * compiles against it and nothing ever should. Its only consumer is
 * `classifyContractChanges` (`./contractCompatibility.ts`) — a comparison between the version
 * committed on `main` and the version this run produced. A lossy projection is a bad source of truth and a
 * perfectly good FINGERPRINT: what matters for comparison is that the same zod always projects to the same
 * bytes, which it does.
 *
 * If you are reading this because the committed JSON Schema looks like ADR-0014's rejected alternative
 * returning: it is the opposite. The rejected alternative made the document the AUTHORITY. This one is a
 * photograph of the authority, taken so that the next photograph can be held up against it.
 *
 * ── ⚠️ WHAT IT CANNOT SEE (say this wherever the artifact is described) ──
 *
 * **A zod `.refine()` / `.superRefine()` predicate does not project into JSON Schema at all.** A business rule
 * that lives inside a refinement can be tightened to the point of rejecting every request a client sends, and
 * this artifact will be byte-identical. So will the classifier's verdict. `.transform()` is the same story from
 * the other end — it cannot be represented, and is RECORDED as unrepresentable rather than dropped, so that a
 * schema becoming unrepresentable is a visible, breaking finding instead of a silent hole.
 *
 * That limit is stated in the generated file itself, in ADR-0014, and here, because an artifact that hides its
 * blind spot is a false guarantee — worse than no artifact, because people stop looking.
 *
 * DESIGN PATTERN: Functional Core. Every export is pure; the write is `generate.ts`'s job.
 */
import { z } from 'zod';
import type { ZodType } from 'zod';

import type { ContractDocument, JsonValue } from './contractCompatibility.js';

/** The committed artifact's filename, inside `packages/schemas/<service>/`. */
export const CONTRACT_FINGERPRINT_FILENAME = 'contract.schema.json';

/** What a service must tell the fingerprint about itself. */
export interface ContractFingerprintMetadata {
    /** The generated package's npm name, e.g. `@kitchensink/schema-food`. */
    readonly schemaPackageName: string;
    /** The exact command that rewrites the artifact. */
    readonly regenerateCommand: string;
}

/** The committed document. Everything but `schemas` is provenance for a human opening the file. */
export interface ContractFingerprint extends ContractDocument {
    /** The do-not-edit banner, since JSON has no comments. */
    readonly $comment: string;
    /** What this comparison is blind to. */
    readonly blindTo: string;
    /** The schema package this fingerprints. */
    readonly contract: string;
    /** How the projection was taken. */
    readonly derivedBy: string;
    /** The statement that keeps this from being read as a codegen input. */
    readonly notCodegen: string;
    /** The command that rewrites this file. */
    readonly regenerate: string;
    /** Exported schema name → its JSON Schema projection. */
    readonly schemas: Readonly<Record<string, JsonValue>>;
}

/** The projection recorded for a schema JSON Schema cannot express. */
interface UnrepresentableProjection {
    /**
     * ⚠️ DELIBERATELY NOT a JSON Schema keyword and deliberately NOT `x-`-prefixed. The classifier waves
     * annotations and `x-` extensions through, and models every keyword it knows; an unknown key like this one
     * falls to its fail-closed sweep, so a schema that STOPS being representable is reported as breaking
     * instead of vanishing into an annotation.
     */
    readonly unrepresentable: string;
}

/**
 * Whether a value is a zod schema from THIS copy of zod.
 *
 * @param value - The exported value.
 * @returns True for a zod schema instance. Pure.
 */
function isZodSchema(value: unknown): value is ZodType {
    return value instanceof z.ZodType;
}

/**
 * Whether a value walks and talks like a zod schema without being an instance of this zod.
 *
 * The only way that happens is TWO copies of zod in the installed tree. It matters because the projection is an
 * `instanceof` filter: every schema from the other copy would fall silently out of the fingerprint, and the
 * artifact would shrink without a word while the gate reported green.
 *
 * @param value - The exported value.
 * @returns True when the value is structurally a zod schema. Pure.
 */
function isForeignZodSchema(value: unknown): boolean {
    if (typeof value !== 'object' || value === null) {
        return false;
    }

    const candidate = value as { readonly _zod?: { readonly def?: { readonly type?: unknown } } };

    return typeof candidate._zod?.def?.type === 'string';
}

/**
 * Project one schema, recording rather than dropping what cannot be represented.
 *
 * @param name - The export's name, used in the recorded reason.
 * @param schema - The zod schema.
 * @returns The JSON Schema projection, or the unrepresentable marker. Pure.
 */
function project(name: string, schema: ZodType): JsonValue | UnrepresentableProjection {
    try {
        // `io: 'output'` is the ruling: the fingerprint describes what the contract PRODUCES, so a `.default()`
        // is guaranteed rather than optional. Taking it in the input direction would describe a different
        // contract, and mixing the two across regenerations would manufacture drift.
        return z.toJSONSchema(schema, { io: 'output' }) as JsonValue;
    } catch (error) {
        return {
            unrepresentable: `${name} cannot be represented in JSON Schema: ${
                error instanceof Error ? error.message : String(error)
            }`,
        };
    }
}

/**
 * Build the fingerprint document from a schema package's module namespace.
 *
 * @param exports - What `packages/schemas/<service>/src/schemas.ts` exports at runtime.
 * @param metadata - The package name and the command that regenerates it.
 * @returns The document, ready to serialize.
 * @throws When the namespace contains no zod schema at all (a fingerprint of nothing would pass forever), or
 *   when it contains a schema built by a SECOND copy of zod (which the `instanceof` filter would silently
 *   drop).
 */
export function buildContractFingerprint(
    exports: Readonly<Record<string, unknown>>,
    metadata: ContractFingerprintMetadata,
): ContractFingerprint {
    const schemas: Record<string, JsonValue> = {};

    for (const name of Object.keys(exports).sort()) {
        const value = exports[name];

        if (isZodSchema(value)) {
            schemas[name] = project(name, value) as JsonValue;

            continue;
        }

        if (isForeignZodSchema(value)) {
            throw new Error(
                `Export '${name}' is structurally a zod schema but is not an instance of this package's zod, ` +
                    'which means a SECOND copy of zod is installed. The fingerprint filters exports with ' +
                    '`instanceof`, so every schema from the other copy would drop out of the published contract ' +
                    'silently. Deduplicate zod before regenerating.',
            );
        }
    }

    if (Object.keys(schemas).length === 0) {
        throw new Error(
            `No zod schema was found among the ${Object.keys(exports).length} export(s) of ` +
                `${metadata.schemaPackageName}. A fingerprint of nothing would be committed, diffed and pass ` +
                'forever while gating nothing. Refusing to write.',
        );
    }

    return {
        $comment:
            '⚠️ GENERATED FILE — DO NOT EDIT. A comparison fingerprint of the published wire contract, ' +
            'regenerated and diffed by CI (`npm run contract:verify`).',
        blindTo:
            'A zod `.refine()`/`.superRefine()` predicate does NOT project into JSON Schema, so a business ' +
            'rule changed inside a refinement is invisible here and to the breaking-change classifier. ' +
            'A `.transform()` is recorded as `unrepresentable` rather than dropped.',
        contract: metadata.schemaPackageName,
        derivedBy: "z.toJSONSchema(schema, { io: 'output' }) over every zod export of ./src/schemas.ts",
        notCodegen:
            'This document GENERATES NOTHING — no type, no zod, no client. It is not the type authority ' +
            '(the zod in ./src is), and it is not ADR-0014 §1’s rejected "derive types through OpenAPI": ' +
            'it exists only to be compared against its own previous version.',
        regenerate: metadata.regenerateCommand,
        schemas,
    };
}

/**
 * Sort every object's keys, at every depth, leaving array order untouched.
 *
 * Object key order is not semantic in JSON; ARRAY order is (`prefixItems` is positional, and `enum` order is
 * how a reader reads it), so the two are treated differently on purpose. Sorting is what makes the committed
 * diff readable: a property added in the middle of a zod object moves one line rather than reflowing the file.
 *
 * @param value - Any JSON value.
 * @returns The same value with object keys sorted. Pure.
 */
export function sortJsonKeysDeep(value: JsonValue): JsonValue {
    if (Array.isArray(value)) {
        return value.map(sortJsonKeysDeep);
    }

    if (typeof value !== 'object' || value === null) {
        return value;
    }

    const source = value as { readonly [key: string]: JsonValue };
    const sorted: Record<string, JsonValue> = {};

    for (const key of Object.keys(source).sort()) {
        sorted[key] = sortJsonKeysDeep(source[key] as JsonValue);
    }

    return sorted;
}

/**
 * Serialize the fingerprint to the exact bytes that get committed.
 *
 * @param fingerprint - The document.
 * @returns 4-space JSON with a trailing newline. Pure.
 */
export function serializeContractFingerprint(fingerprint: ContractFingerprint): string {
    return `${JSON.stringify(sortJsonKeysDeep(fingerprint as unknown as JsonValue), null, 4)}\n`;
}
