import type { ResolvedContentSource } from './contentSource.js';

/**
 * The subset of `@docusaurus/plugin-content-docs` options this site derives.
 *
 * A `type`, not an `interface`, for a concrete reason rather than taste: Docusaurus types a plugin's
 * options as `{id?: string} & {[key: string]: unknown}`, and TypeScript gives a type alias an
 * implicit index signature while an interface gets none — so an interface here is rejected at the
 * `PluginConfig` boundary and the only interface-preserving repairs are a cast or an index signature
 * of our own, both of which trade a checked shape for an unchecked one.
 */
export type DocsPluginOptions = {
    readonly id: string;
    /** Site-directory-relative path Docusaurus mounts. */
    readonly path: string;
    readonly routeBasePath: string;
    /** Mutable by necessity: Docusaurus's own `include` option is `string[]`, not `readonly string[]`. */
    readonly include: string[];
    readonly sidebarPath: string;
};

/**
 * Derives one `@docusaurus/plugin-content-docs` instance from a resolved content source.
 *
 * Pattern: Adapter — the registry speaks in repo-root-relative paths (comparable, testable values)
 * and Docusaurus speaks in site-directory-relative ones. This is the only place the two meet.
 *
 * There is deliberately NO `editUrl`. Half of what this site serves is generated output whose edit
 * target is a generator, not the rendered file, and an "Edit this page" link pointing at generated
 * Markdown invites exactly the hand-edit that the next generator run would silently discard.
 *
 * @param source - A resolved source; `mountPath` already accounts for the placeholder fallback.
 * @param siteToRepoRoot - Relative hop from the site directory up to the repository root.
 */
export function buildDocsPluginOptions(source: ResolvedContentSource, siteToRepoRoot: string): DocsPluginOptions {
    return {
        id: source.id,
        path: `${siteToRepoRoot}/${source.mountPath}`,
        routeBasePath: source.routeBasePath,
        include: [...source.include],
        // Every instance shares one autogenerated sidebar: navigation is DERIVED from the corpus on
        // disk, never authored, so a new ADR appears without anyone editing this package.
        sidebarPath: './sidebars.ts',
    };
}
