/**
 * REAL `Converse` response bodies, taken from AWS's own documentation — NOT invented here.
 *
 * ⛔ WHY THE PROVENANCE MATTERS. A response body an engineer writes to match the parser they are about to
 * write asserts nothing: it passes whether the parser is right or wrong, because both sides came from the
 * same guess. These bodies are copied from primary AWS sources so the parser is tested against the shape the
 * service actually returns:
 *
 *  - {@link NOVA_TEXT_RESPONSE} — the response body published in the
 *    [Converse API reference](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html)
 *    and reproduced in
 *    [Inference using the Converse API](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html),
 *    including its real token counts (30 / 628 / 658) and latency (1275 ms). Retrieved 2026-08-21.
 *  - The `stopReason` values come from the SDK's OWN `StopReason` enum (`@aws-sdk/client-bedrock-runtime`),
 *    which is why `schemas.ts` does not restate them.
 *
 * ⚠️ NOTHING HERE FABRICATES A CACHE HIT. ADR-0024 §5 is explicit that `cacheReadInputTokens` /
 * `cacheWriteInputTokens` cannot be produced at this prompt size on any candidate model, so a fixture
 * claiming one would prove only that our arithmetic compiles. The cache fields are therefore ABSENT from
 * every body below — which is exactly what the wire looks like (`Required: No`), and is the case the parser
 * has to get right.
 */

/**
 * The documented happy-path body: one assistant text block, `end_turn`, and a full `usage`.
 *
 * `readonly` and deeply frozen so one test cannot mutate the fixture another test reads.
 */
export const NOVA_TEXT_RESPONSE = Object.freeze({
    output: {
        message: {
            content: [{ text: '<text generated by the model>' }],
            role: 'assistant',
        },
    },
    stopReason: 'end_turn',
    usage: {
        inputTokens: 30,
        outputTokens: 628,
        totalTokens: 658,
    },
    metrics: {
        latencyMs: 1275,
    },
});

/**
 * The same envelope carrying the JSON verdict this gate actually asks for.
 *
 * The envelope is {@link NOVA_TEXT_RESPONSE}'s, byte for byte, with only the text block replaced — because
 * the envelope is the part that must not be invented and the text is the part under test.
 *
 * @param text - The assistant text to place in the single content block.
 * @param overrides - `stopReason` / `usage` replacements for the failure shapes.
 * @returns A response body shaped exactly like AWS's documented one. Pure.
 */
export function converseResponseWith(
    text: string,
    overrides: { readonly stopReason?: string; readonly usage?: unknown } = {},
): unknown {
    return {
        output: { message: { content: [{ text }], role: 'assistant' } },
        stopReason: overrides.stopReason ?? 'end_turn',
        ...(Object.hasOwn(overrides, 'usage')
            ? { usage: overrides.usage }
            : { usage: { inputTokens: 660, outputTokens: 42, totalTokens: 702 } }),
        metrics: { latencyMs: 1275 },
    };
}
