/**
 * WHO OWNS WHICH WIRE CONTRACT — the ONE expectation both halves of `npm run contract:verify` are measured
 * against (`docs/CODING_STANDARDS.md` §15.2.5).
 *
 * ── THE HOLE THIS CLOSES, AND WHY IT WAS INVISIBLE ──
 *
 * `contract:verify` is "regenerate, then require the tree to be unchanged". Both halves used to work from a
 * different, implicit idea of what the contract SET is:
 *
 *  - the regeneration ran `turbo run contract:generate --filter='./packages/services/*'` — a PATH glob. Measured:
 *    a filter that matches a package with no such task prints `WARNING  No tasks were executed as part of this
 *    run` and exits **0**. So a service that loses or renames its `contract:generate` script simply stops being
 *    regenerated, with a zero exit.
 *  - the gate then counted TRACKED `packages/schemas/*\/openapi.yaml` files and reported "…(3 document(s)
 *    checked)". Those are the files that EXIST, not the ones that were regenerated. With a service dropped out,
 *    the gate finds no diff — because nothing rewrote that service's document — and prints proof it never
 *    obtained.
 *
 * The two failures compose into the worst case a gate can have: a stale published contract, certified green.
 *
 * ── THE EXPECTATION, AND WHY IT IS DERIVED RATHER THAN LISTED ──
 *
 * A hardcoded list of services is the same hole one level up: it goes stale silently, and a new service's
 * contract is then ungated while everyone believes it is covered. So the set is DERIVED from a correspondence
 * that already exists in the tree and is checked in BOTH directions:
 *
 *  - every `packages/schemas/<name>` delegates its own `contract:generate` to exactly one service
 *    (`npm run contract:generate --workspace=<service>`), and that service must exist and must declare the
 *    script; and
 *  - every service that declares a `contract:generate` script must be named by exactly one schema package.
 *
 * Either direction breaking is reported as a failure naming the package, rather than shrinking the expected set —
 * which is the whole point: a contract that drops out of the pipeline must be loud.
 *
 * @sideEffect {@link discoverContractOwners} reads `package.json` files; everything else here is pure.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

/** Where generated contract packages live, relative to the repo root. */
const SCHEMAS_DIR = 'packages/schemas';

/** Where the services that author the contracts live, relative to the repo root. */
const SERVICES_DIR = 'packages/services';

/** The script name a service and its schema package both use. */
const GENERATE_SCRIPT = 'contract:generate';

/**
 * The service a schema package's delegating `contract:generate` script names.
 *
 * Matched on `--workspace=<name>` rather than by convention over the directory name, because the correspondence
 * is not derivable from the names: `packages/schemas/identity` is generated by `@kitchensink/identity-service`,
 * which lives in `packages/services/identity`.
 *
 * @param {string | undefined} script - The schema package's `contract:generate` script, if it has one.
 * @returns {string | undefined} The npm name of the generating service, or `undefined` when the script is absent
 *   or does not name a workspace. Pure.
 */
export function parseDelegatedWorkspace(script) {
    if (typeof script !== 'string') {
        return undefined;
    }

    return /--workspace=(\S+)/u.exec(script)?.[1];
}

/**
 * Read a `package.json`, or `undefined` when it is not there.
 *
 * @param {string} manifestPath - Absolute path to the manifest.
 * @returns {{ name?: string, scripts?: Record<string, string> } | undefined} The parsed manifest.
 * @sideEffect Reads the filesystem.
 */
function readManifest(manifestPath) {
    if (!existsSync(manifestPath)) {
        return undefined;
    }

    return JSON.parse(readFileSync(manifestPath, 'utf8'));
}

/**
 * Directory names of the immediate subdirectories of `parent` that contain a `package.json`.
 *
 * @param {string} parent - Absolute path.
 * @returns {string[]} Sorted directory names, so the expectation is order-stable.
 * @sideEffect Reads the filesystem.
 */
function packageDirectories(parent) {
    if (!existsSync(parent)) {
        return [];
    }

    return readdirSync(parent, { withFileTypes: true })
        .filter((entry) => entry.isDirectory() && existsSync(path.join(parent, entry.name, 'package.json')))
        .map((entry) => entry.name)
        .sort();
}

/**
 * @typedef {object} ContractOwner
 * @property {string} schemaPackageName - e.g. `@kitchensink/schema-food`.
 * @property {string} documentPath - Repo-relative path of the generated document, e.g.
 *   `packages/schemas/food/openapi.yaml`.
 * @property {string} serviceName - npm name of the service that regenerates it.
 */

/**
 * @typedef {object} ContractOwnership
 * @property {ContractOwner[]} owners - One per generated contract package, sorted by `documentPath`.
 * @property {string[]} problems - Human-readable breaks in the correspondence. Non-empty means the pipeline
 *   cannot state what it is supposed to regenerate, which is a failure and never a smaller expectation.
 */

/**
 * Discover which service regenerates each generated contract package.
 *
 * @param {string} repoRoot - Absolute path of the repository root.
 * @returns {ContractOwnership} The expectation, plus every break in it.
 * @sideEffect Reads the `package.json` of every schema package and every service.
 */
export function discoverContractOwners(repoRoot) {
    const problems = [];
    const owners = [];

    /** npm name → repo-relative directory, for every service package. */
    const services = new Map();

    for (const directory of packageDirectories(path.join(repoRoot, SERVICES_DIR))) {
        const manifest = readManifest(path.join(repoRoot, SERVICES_DIR, directory, 'package.json'));

        if (manifest?.name !== undefined) {
            services.set(manifest.name, { directory, manifest });
        }
    }

    for (const directory of packageDirectories(path.join(repoRoot, SCHEMAS_DIR))) {
        const schemaDir = `${SCHEMAS_DIR}/${directory}`;
        const manifest = readManifest(path.join(repoRoot, schemaDir, 'package.json'));
        const serviceName = parseDelegatedWorkspace(manifest?.scripts?.[GENERATE_SCRIPT]);

        if (serviceName === undefined) {
            problems.push(
                `${schemaDir}/package.json has no '${GENERATE_SCRIPT}' script naming the service that ` +
                    'regenerates it, so nothing in the pipeline knows this contract exists.',
            );

            continue;
        }

        const service = services.get(serviceName);

        if (service === undefined) {
            problems.push(
                `${schemaDir} delegates '${GENERATE_SCRIPT}' to '${serviceName}', which is not a package under ` +
                    `${SERVICES_DIR}/. Renamed?`,
            );

            continue;
        }

        if (service.manifest.scripts?.[GENERATE_SCRIPT] === undefined) {
            problems.push(
                `${serviceName} (${SERVICES_DIR}/${service.directory}) has no '${GENERATE_SCRIPT}' script, so ` +
                    `${schemaDir}/openapi.yaml is NEVER regenerated — and the drift check then finds no diff and ` +
                    'reports a clean contract it did not verify.',
            );

            continue;
        }

        owners.push({
            schemaPackageName: manifest?.name ?? schemaDir,
            documentPath: `${schemaDir}/openapi.yaml`,
            serviceName,
        });
    }

    // The other direction: a service that generates a contract nobody publishes. Left unchecked, a new service's
    // contract is regenerated into a package no gate looks at.
    const claimed = new Set(owners.map((owner) => owner.serviceName));

    for (const [name, service] of services) {
        if (service.manifest.scripts?.[GENERATE_SCRIPT] !== undefined && !claimed.has(name)) {
            problems.push(
                `${name} declares '${GENERATE_SCRIPT}' but no ${SCHEMAS_DIR}/* package delegates to it, so its ` +
                    'generated contract is outside the drift gate.',
            );
        }
    }

    return {
        owners: owners.sort((left, right) => (left.documentPath < right.documentPath ? -1 : 1)),
        problems,
    };
}

/**
 * Render the ownership problems as an operator-facing report.
 *
 * @param {readonly string[]} problems - The problems.
 * @returns {string} The report body, in Markdown. Pure.
 */
export function formatOwnershipReport(problems) {
    return [
        '### The wire-contract pipeline cannot state what it regenerates',
        '',
        'Every `packages/schemas/*` package must delegate its `contract:generate` to a service that declares',
        'that script, and every such service must be named by exactly one schema package. Otherwise a contract',
        'silently stops being regenerated, and the drift check then passes by finding no diff:',
        '',
        '```',
        ...[...problems].sort(),
        '```',
        '',
        'Fix the correspondence. Do not narrow the check to the packages that still line up.',
    ].join('\n');
}
