/**
 * THE STORAGE-CAPACITY GATE for the food (ingredient) service.
 *
 * > For every wire field that writes to a bounded column, the zod max must be ≤ what the column can
 * > physically store.
 *
 * The invariant, the machinery and the reasoning are shared — they live once in
 * `@kitchensink/contract-gen`'s `storageCapacity.ts`, which was built for the recipe service, where nine
 * fields were answering `500` (`22003 … out of range for type integer`) for what were plainly bad requests.
 *
 * ── THIS SERVICE CURRENTLY HAS NO WIRE FIELD THAT WRITES A BOUNDED COLUMN, AND THAT IS THE POINT ──
 *
 * All three bounded columns here are server-managed, so every entry below is an exemption with a reason. The
 * gate is still worth running — arguably it is worth MORE here — because it is exhaustive over COLUMNS: the
 * day someone adds a `varchar(n)`, `smallint` or `numeric(p, s)` column, this test fails until the new column
 * is either bound to the wire field that writes it or exempted with a stated reason. A gate that only listed
 * today's known defects would catch nothing new; this one catches the next one on arrival.
 *
 * It has already earned that: the food schema's `bigserial` primary key is what made
 * `describeColumnCapacity` throw on an unmapped column type rather than silently reporting it unbounded.
 *
 * ⚠️ ASSERTION, NOT DERIVATION. Nothing here generates zod from drizzle and no drizzle type becomes a wire
 * type — food's `FoodStatus` taking its WIRE type from a drizzle enum in `dao/index.js` is the exact leak
 * §15.2 removed. This test reads both models and compares them.
 */
import { describe, expect, it } from 'vitest';
import { z } from 'zod';
import { auditStorageCapacity, collectBoundedColumns, formatStorageCapacityFindings } from '@kitchensink/contract-gen';
import type { ColumnAccount } from '@kitchensink/contract-gen';

import * as schema from '../index.js';

/** One entry per bounded column. Exhaustive by construction — the audit fails on anything unlisted. */
const accounts: readonly ColumnAccount[] = [
    {
        table: 'fetch_queue',
        column: 'attempts',
        why: 'Server-incremented retry counter on the fetch queue; no wire field sets it.',
    },
    {
        table: 'fetch_queue',
        column: 'request_count',
        why: 'Server-incremented demand counter (how many callers have asked for this food); no wire field sets it.',
    },
    {
        table: 'source_call_log',
        column: 'id',
        why: 'bigserial surrogate key, generated by the sequence; no wire field sets it.',
    },
];

describe('storage capacity — every wire bound fits the column it writes', () => {
    it('holds for every bounded column in the food service', () => {
        expect(formatStorageCapacityFindings(auditStorageCapacity({ tables: schema, accounts }))).toBe('');
    });

    it('accounts for EVERY bounded column, so a new one fails this test on arrival', () => {
        const bounded = collectBoundedColumns(schema).map((column) => `${column.table}.${column.column}`);
        const accounted = accounts.map((account) => `${account.table}.${account.column}`);

        expect([...accounted].sort()).toEqual([...bounded].sort());
    });

    it('recognizes every column type this schema uses (it THROWS on one it does not)', () => {
        expect(() => collectBoundedColumns(schema)).not.toThrow();
    });

    it('would REPORT a wire field that outgrew its column, so the exemptions are not load-bearing', () => {
        // Proves the audit is actually checking, not just tolerating `why` entries: bind one exempted column
        // to an unbounded integer and the finding must appear. `z.number().int()` promises only a SAFE integer
        // (9007199254740991) — 4.2 million times the int4 ceiling — which is why this class of defect hides.
        const findings = auditStorageCapacity({
            tables: schema,
            accounts: accounts.map((account) =>
                account.column === 'attempts'
                    ? { ...account, why: undefined, fields: [{ field: 'probe', schema: z.number().int().positive() }] }
                    : account,
            ),
        });

        expect(formatStorageCapacityFindings(findings)).toMatch(/fetch_queue\.attempts/u);
    });
});
