import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * ONE sidebar definition, shared by every docs-plugin instance.
 *
 * It is fully autogenerated from the directory tree on disk, which is the point: a new ADR, a new
 * runbook or a freshly generated infrastructure page appears in navigation without anyone editing
 * this package. An authored sidebar would be a second, hand-maintained list of what the corpus
 * contains — and a list that can disagree with the corpus is the drift this site exists to remove.
 *
 * The instance mounting it decides WHICH files it sees; that allowlist lives in
 * `src/content/contentRegistry.ts`.
 *
 * Default-exported because Docusaurus resolves `sidebarPath` modules by their default export.
 */
const sidebars: SidebarsConfig = {
    sections: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
