#!/usr/bin/env node
/**
 * Fetch Clerk keys from AWS Secrets Manager and write to .env.local
 *
 * Usage:
 *   node scripts/fetch-secrets.mjs [--stage sandbox|dev|prod]
 *
 * Requires AWS credentials with SecretsManager read access.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * The stages this script is documented to accept. An allowlist rather than a free string: `STAGE` reaches an
 * AWS call, and the usage note above already promises exactly these three — so anything else is a typo that
 * should fail here, naming the mistake, instead of becoming a "secret not found" further down.
 */
const STAGES = ['sandbox', 'dev', 'prod'];

const STAGE = process.argv.find((a) => a.startsWith('--stage='))?.split('=')[1] ?? 'sandbox';

if (!STAGES.includes(STAGE)) {
    console.error(`Unknown --stage '${STAGE}'. Expected one of: ${STAGES.join(', ')}.`);
    process.exit(1);
}

const SECRET_ID = `kitchensink/${STAGE}/identity/keys`;
const ENV_FILE = resolve(import.meta.dirname, '../.env.local');

try {
    // `execFileSync` with an argument ARRAY, never a shell string: `SECRET_ID` is built from an argv value, so
    // interpolating it into a command line makes the shell an attack surface for whoever runs this. Passing
    // argv straight through spawns `aws` with no shell at all, which also removes the quoting hazard.
    const raw = execFileSync(
        'aws',
        ['secretsmanager', 'get-secret-value', '--secret-id', SECRET_ID, '--query', 'SecretString', '--output', 'text'],
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
    );
    const { PUBLISHABLE_KEY: publishableKey, SECRET_KEY: secretKey } = JSON.parse(raw.trim());

    if (!publishableKey || !secretKey) {
        throw new Error('Missing PUBLISHABLE_KEY or SECRET_KEY in secret');
    }

    const lines = [
        '# Auto-generated by scripts/fetch-secrets.mjs',
        '# Do NOT commit this file — .env.local is gitignored',
        '',
        '# Clerk authentication (sandbox dev instance — pk_test/sk_test, safe for localhost + Playwright e2e)',
        `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${publishableKey}`,
        `CLERK_SECRET_KEY=${secretKey}`,
    ];

    // NOTE: the API endpoints are deliberately NOT written here. They live in the committed
    // `.env.development`, which Next loads for `next dev` and never for `next build` — so local work is
    // zero-config while a deployed build still cannot inherit a localhost default. This script only
    // fetches SECRETS, which is why it stopped emitting `NEXT_PUBLIC_*_API_URL`. To develop against a
    // deployed backend, set the endpoint in `.env.local` yourself; it wins over `.env.development`.

    writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
    console.log(`Wrote ${ENV_FILE}`);
} catch (err) {
    console.error('Failed to fetch secrets:', err.message);
    process.exit(1);
}
