#!/usr/bin/env node
/**
 * Fetch Clerk keys from AWS Secrets Manager and write to .env.local
 *
 * Usage:
 *   node scripts/fetch-secrets.mjs [--stage sandbox|dev|prod]
 *
 * Requires AWS credentials with SecretsManager read access.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const STAGE = process.argv.find((a) => a.startsWith('--stage='))?.split('=')[1] ?? 'sandbox';
const SECRET_ID = `kitchensink/${STAGE}/identity/keys`;
const ENV_FILE = resolve(import.meta.dirname, '../.env.local');

try {
    const raw = execSync(
        `aws secretsmanager get-secret-value --secret-id ${SECRET_ID} --query SecretString --output text`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
    );
    const { PUBLISHABLE_KEY: publishableKey, SECRET_KEY: secretKey } = JSON.parse(raw.trim());

    if (!publishableKey || !secretKey) {
        throw new Error('Missing PUBLISHABLE_KEY or SECRET_KEY in secret');
    }

    const lines = [
        '# Auto-generated by scripts/fetch-secrets.mjs',
        '# Do NOT commit this file — .env.local is gitignored',
        '',
        '# Clerk authentication (sandbox dev instance — pk_test/sk_test, safe for localhost + Playwright e2e)',
        `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${publishableKey}`,
        `CLERK_SECRET_KEY=${secretKey}`,
    ];

    // NOTE: the API endpoints are deliberately NOT written here. They live in the committed
    // `.env.development`, which Next loads for `next dev` and never for `next build` — so local work is
    // zero-config while a deployed build still cannot inherit a localhost default. This script only
    // fetches SECRETS, which is why it stopped emitting `NEXT_PUBLIC_*_API_URL`. To develop against a
    // deployed backend, set the endpoint in `.env.local` yourself; it wins over `.env.development`.

    writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
    console.log(`Wrote ${ENV_FILE}`);
} catch (err) {
    console.error('Failed to fetch secrets:', err.message);
    process.exit(1);
}
