/**
 * GENERATED by `npm run fixtures:generate --workspace=@commise/features-recipes`
 * (`scripts/seedVariantsFixture.ts`). Do not edit it by hand:
 * `scripts/__tests__/seedVariantsFixture.test.ts` fails when it and its sources disagree.
 *
 * Live variants of six roots from the committed curated seed, in the wire shape:
 * `packages/services/food-service/src/foods/seed/data/curatedCatalog.jsonl`. They are the fixtures
 * `docs/design/ingredientSpecialization.md` §S8.3 names, so the grouping rule is tested on real data at its
 * boundaries.
 *
 * Calories are the USDA values in `docs/design/variantDetailsMockup.html`, present only for the roots that file covers
 * in full. The others carry parts only: their tests are about structure, which calories do not change.
 */
import type { VariantView } from '@kitchensink/food-service-client';

/** `boneless skinless chicken thighs`: 7 live variants. */
export const BONELESS_SKINLESS_CHICKEN_THIGHS: readonly VariantView[] = [
    { id: 'fdc:172387', parts: [{ attribute: 'cookingMethod', text: 'fried' }], caloriesPer100g: 218 },
    { id: 'fdc:172388', parts: [{ attribute: 'cookingMethod', text: 'roasted' }], caloriesPer100g: 179 },
    { id: 'fdc:172389', parts: [{ attribute: 'cookingMethod', text: 'stewed' }], caloriesPer100g: 195 },
    { id: 'fdc:172853', parts: [{ attribute: 'cookingMethod', text: 'braised' }], caloriesPer100g: 176 },
    { id: 'fdc:172859', parts: [{ attribute: 'pack', text: 'with added solution' }], caloriesPer100g: 110 },
    {
        id: 'fdc:174500',
        parts: [
            { attribute: 'pack', text: 'with added solution' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
        caloriesPer100g: 164,
    },
    {
        id: 'fdc:172858',
        parts: [
            { attribute: 'pack', text: 'with added solution' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 164,
    },
];

/** `boneless skinless chicken breasts`: 8 live variants. */
export const BONELESS_SKINLESS_CHICKEN_BREASTS: readonly VariantView[] = [
    { id: 'fdc:171078', parts: [{ attribute: 'cookingMethod', text: 'fried' }], caloriesPer100g: 187 },
    { id: 'fdc:171477', parts: [{ attribute: 'cookingMethod', text: 'roasted' }], caloriesPer100g: 165 },
    { id: 'fdc:171478', parts: [{ attribute: 'cookingMethod', text: 'stewed' }], caloriesPer100g: 151 },
    { id: 'fdc:171509', parts: [{ attribute: 'pack', text: 'with added solution' }], caloriesPer100g: 108 },
    { id: 'fdc:171534', parts: [{ attribute: 'cookingMethod', text: 'grilled' }], caloriesPer100g: 151 },
    {
        id: 'fdc:171535',
        parts: [
            { attribute: 'pack', text: 'with added solution' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 145,
    },
    { id: 'fdc:331960', parts: [{ attribute: 'cookingMethod', text: 'braised' }], caloriesPer100g: 166 },
    {
        id: 'fdc:171536',
        parts: [
            { attribute: 'pack', text: 'with added solution' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
        caloriesPer100g: 148,
    },
];

/** `beef brisket`: 40 live variants. */
export const BEEF_BRISKET: readonly VariantView[] = [
    {
        id: 'fdc:169432',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 280,
    },
    {
        id: 'fdc:169440',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 221,
    },
    {
        id: 'fdc:169469',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 198,
    },
    {
        id: 'fdc:169488',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 289,
    },
    {
        id: 'fdc:169555',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 205,
    },
    {
        id: 'fdc:170210',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 205,
    },
    {
        id: 'fdc:170601',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 212,
    },
    {
        id: 'fdc:170613',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 213,
    },
    {
        id: 'fdc:171818',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 203,
    },
    {
        id: 'fdc:173130',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 298,
    },
    {
        id: 'fdc:174047',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 196,
    },
    {
        id: 'fdc:174717',
        parts: [
            { attribute: 'cut', text: 'navel end' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'cookingMethod', text: 'braised' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 265,
    },
    {
        id: 'fdc:174739',
        parts: [
            { attribute: 'cut', text: 'navel end' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'cookingMethod', text: 'braised' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 453,
    },
    {
        id: 'fdc:174768',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 189,
    },
    {
        id: 'fdc:173128',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
        caloriesPer100g: 278,
    },
    {
        id: 'fdc:173129',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
        caloriesPer100g: 276,
    },
    {
        id: 'fdc:174048',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 127,
    },
    {
        id: 'fdc:174057',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
        caloriesPer100g: 129,
    },
    {
        id: 'fdc:174718',
        parts: [
            { attribute: 'cut', text: 'navel end' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 194,
    },
    {
        id: 'fdc:174740',
        parts: [
            { attribute: 'cut', text: 'navel end' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 345,
    },
    {
        id: 'fdc:174766',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
        caloriesPer100g: 124,
    },
    {
        id: 'fdc:168656',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 132,
    },
    {
        id: 'fdc:168657',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
        caloriesPer100g: 137,
    },
    {
        id: 'fdc:168658',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
        caloriesPer100g: 124,
    },
    {
        id: 'fdc:168666',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 277,
    },
    {
        id: 'fdc:168714',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 165,
    },
    {
        id: 'fdc:168743',
        parts: [
            { attribute: 'cut', text: 'flat half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
        caloriesPer100g: 169,
    },
    {
        id: 'fdc:168607',
        parts: [
            { attribute: 'cut', text: 'whole' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 157,
    },
    {
        id: 'fdc:168664',
        parts: [
            { attribute: 'cut', text: 'whole' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 253,
    },
    {
        id: 'fdc:168665',
        parts: [
            { attribute: 'cut', text: 'whole' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 331,
    },
    {
        id: 'fdc:170611',
        parts: [
            { attribute: 'cut', text: 'whole' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 291,
    },
    {
        id: 'fdc:170612',
        parts: [
            { attribute: 'cut', text: 'whole' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 218,
    },
    {
        id: 'fdc:169489',
        parts: [
            { attribute: 'cut', text: 'point half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
        caloriesPer100g: 267,
    },
    {
        id: 'fdc:173074',
        parts: [
            { attribute: 'cut', text: 'point end' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 125,
    },
    {
        id: 'fdc:174742',
        parts: [
            { attribute: 'cut', text: 'point end' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 163,
    },
    {
        id: 'fdc:169490',
        parts: [
            { attribute: 'cut', text: 'point half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 349,
    },
    {
        id: 'fdc:170211',
        parts: [
            { attribute: 'cut', text: 'point half' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 358,
    },
    {
        id: 'fdc:170212',
        parts: [
            { attribute: 'cut', text: 'point half' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
        caloriesPer100g: 244,
    },
    {
        id: 'fdc:173073',
        parts: [
            { attribute: 'cut', text: 'point end' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'cookingMethod', text: 'braised' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 202,
    },
    {
        id: 'fdc:174741',
        parts: [
            { attribute: 'cut', text: 'point end' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'cookingMethod', text: 'braised' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
        caloriesPer100g: 250,
    },
];

/** `ground beef`: 42 live variants. */
export const GROUND_BEEF: readonly VariantView[] = [
    { id: 'fdc:168608', parts: [{ attribute: 'formOrVariety', text: 'grass-fed' }] },
    { id: 'fdc:168652', parts: [{ attribute: 'fat', text: '70/30' }] },
    { id: 'fdc:171790', parts: [{ attribute: 'fat', text: '95/5' }] },
    { id: 'fdc:173110', parts: [{ attribute: 'fat', text: '93/7' }] },
    { id: 'fdc:173111', parts: [{ attribute: 'fat', text: '97/3' }] },
    { id: 'fdc:174037', parts: [{ attribute: 'fat', text: '75/25' }] },
    {
        id: 'fdc:168650',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '70/30' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:168651',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '70/30' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:169473',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '70/30' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:169474',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '70/30' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:171791',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '95/5' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:171792',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '95/5' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:171793',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '90/10' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:171794',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '90/10' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:171795',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '90/10' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:171797',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '80/20' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:171798',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '80/20' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:171799',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '80/20' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:171800',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '80/20' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:171801',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '75/25' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:172161',
        parts: [
            { attribute: 'fat', text: 'unspecified fat' },
            { attribute: 'cookingMethod', text: 'cooked' },
        ],
    },
    {
        id: 'fdc:173068',
        parts: [
            { attribute: 'formOrVariety', text: 'grass-fed' },
            { attribute: 'fat', text: '85/15' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:173112',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '97/3' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:173113',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '97/3' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:173114',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '97/3' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:174028',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '95/5' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:174029',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '95/5' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:174031',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '90/10' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:174032',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '85/15' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:174033',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '85/15' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:174034',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '85/15' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:174035',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '85/15' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:174038',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '75/25' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:174039',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '75/25' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:174040',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '75/25' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:174752',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '93/7' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:174753',
        parts: [
            { attribute: 'formOrVariety', text: 'patty' },
            { attribute: 'fat', text: '93/7' },
            { attribute: 'cookingMethod', text: 'pan-broiled' },
        ],
    },
    {
        id: 'fdc:174754',
        parts: [
            { attribute: 'formOrVariety', text: 'loaf' },
            { attribute: 'fat', text: '93/7' },
            { attribute: 'cookingMethod', text: 'baked' },
        ],
    },
    {
        id: 'fdc:174755',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '93/7' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    {
        id: 'fdc:174756',
        parts: [
            { attribute: 'formOrVariety', text: 'crumbles' },
            { attribute: 'fat', text: '97/3' },
            { attribute: 'cookingMethod', text: 'pan-browned' },
        ],
    },
    { id: 'fdc:2514744', parts: [{ attribute: 'fat', text: '80/20' }] },
    { id: 'fdc:2514743', parts: [{ attribute: 'fat', text: '90/10' }] },
];

/** `beef chuck roast`: 73 live variants. */
export const BEEF_CHUCK_ROAST: readonly VariantView[] = [
    {
        id: 'fdc:168667',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:168669',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:169492',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170213',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170614',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170615',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170616',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171817',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:174050',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:174767',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:168668',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:168670',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:169491',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:174051',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:174765',
        parts: [
            { attribute: 'cut', text: 'arm pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:169446',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast or steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:169445',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast or steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:170603',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast or steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:170813',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast or steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:170814',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast or steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:170815',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast or steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:169444',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170214',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170216',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170217',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170618',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171208',
        parts: [
            { attribute: 'cut', text: 'under blade pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:168671',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:168673',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:169494',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170215',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170617',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:168672',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:169493',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:169495',
        parts: [
            { attribute: 'cut', text: 'blade roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:168730',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:169553',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:171198',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171199',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171200',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171224',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171225',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171226',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171780',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/4-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:171784',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:174019',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:174023',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:174027',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:169480',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast or steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:169481',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast or steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:169482',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast or steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:170818',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast or steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:170819',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast or steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:173349',
        parts: [
            { attribute: 'cut', text: 'shoulder pot roast or steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:174018',
        parts: [
            { attribute: 'cut', text: 'clod roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/4-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:173097',
        parts: [
            { attribute: 'cut', text: 'bolar blade' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'cookingMethod', text: 'fast roasted' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:173098',
        parts: [
            { attribute: 'cut', text: 'bolar blade' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:174715',
        parts: [
            { attribute: 'cut', text: 'bolar blade' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'cookingMethod', text: 'fast roasted' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:174716',
        parts: [
            { attribute: 'cut', text: 'bolar blade' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:170811',
        parts: [
            { attribute: 'cut', text: 'under blade steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:170812',
        parts: [
            { attribute: 'cut', text: 'under blade steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171207',
        parts: [
            { attribute: 'cut', text: 'under blade steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171217',
        parts: [
            { attribute: 'cut', text: 'under blade steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171218',
        parts: [
            { attribute: 'cut', text: 'under blade steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:171219',
        parts: [
            { attribute: 'cut', text: 'under blade steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
    {
        id: 'fdc:168731',
        parts: [
            { attribute: 'cut', text: 'shoulder steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:168732',
        parts: [
            { attribute: 'cut', text: 'shoulder steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171781',
        parts: [
            { attribute: 'cut', text: 'shoulder steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171785',
        parts: [
            { attribute: 'cut', text: 'shoulder steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171786',
        parts: [
            { attribute: 'cut', text: 'shoulder steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171789',
        parts: [
            { attribute: 'cut', text: 'shoulder steak' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    { id: 'fdc:2646174', parts: [{ attribute: 'grade', text: 'choice' }] },
    {
        id: 'fdc:171782',
        parts: [
            { attribute: 'cut', text: 'clod steak' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '1/4-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'braised' },
        ],
    },
];

/** `beef ribeye steak`: 75 live variants. */
export const BEEF_RIBEYE_STEAK: readonly VariantView[] = [
    {
        id: 'fdc:173058',
        parts: [
            { attribute: 'formOrVariety', text: 'petite roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:173059',
        parts: [
            { attribute: 'formOrVariety', text: 'petite roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:173060',
        parts: [
            { attribute: 'formOrVariety', text: 'petite roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:174696',
        parts: [
            { attribute: 'formOrVariety', text: 'petite roast or filet' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:174697',
        parts: [
            { attribute: 'formOrVariety', text: 'petite roast or filet' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:174698',
        parts: [
            { attribute: 'formOrVariety', text: 'petite roast or filet' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:174701',
        parts: [
            { attribute: 'formOrVariety', text: 'filet' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:174702',
        parts: [
            { attribute: 'formOrVariety', text: 'filet' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:174703',
        parts: [
            { attribute: 'formOrVariety', text: 'filet' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:170838',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:170839',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:170840',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:170841',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:171235',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:171735',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'formOrVariety', text: 'grass-fed' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:172143',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:172151',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:172152',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:172156',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:173380',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:173382',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:173389',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:173393',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:173394',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:173403',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:173404',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:173975',
        parts: [
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'formOrVariety', text: 'grass-fed' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:171209',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171232',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171233',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171236',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171237',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:171238',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:172142',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:172144',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:172164',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:172165',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173381',
        parts: [
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173385',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173386',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173387',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173390',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173391',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173392',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173401',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'grilled' },
        ],
    },
    {
        id: 'fdc:173402',
        parts: [
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-off' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
        ],
    },
    {
        id: 'fdc:173101',
        parts: [
            { attribute: 'cut', text: 'cube roll' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'cookingMethod', text: 'fast roasted' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:174719',
        parts: [
            { attribute: 'cut', text: 'cube roll' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'cookingMethod', text: 'fast roasted' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:173102',
        parts: [
            { attribute: 'cut', text: 'cube roll' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:174720',
        parts: [
            { attribute: 'cut', text: 'cube roll' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'origin', text: 'product of New Zealand' },
        ],
    },
    {
        id: 'fdc:168612',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:168621',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
        ],
    },
    {
        id: 'fdc:169437',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
        ],
    },
    {
        id: 'fdc:168648',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:169436',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:169438',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:169556',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:169557',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'cut', text: 'eye' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: '0-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'broiled' },
        ],
    },
    {
        id: 'fdc:171737',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'formOrVariety', text: 'Wagyu' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'grade', text: 'marble score 4/5' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:171738',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'formOrVariety', text: 'Wagyu' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'grade', text: 'marble score 9' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:171740',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'formOrVariety', text: 'Wagyu' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'grade', text: 'marble score 4/5' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:171741',
        parts: [
            { attribute: 'cut', text: 'small end' },
            { attribute: 'formOrVariety', text: 'steak or roast' },
            { attribute: 'formOrVariety', text: 'Wagyu' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'grade', text: 'marble score 9' },
            { attribute: 'origin', text: 'product of Australia' },
        ],
    },
    {
        id: 'fdc:170836',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:170837',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:170842',
        parts: [
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:171210',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:171239',
        parts: [
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:172149',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:172150',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:172153',
        parts: [
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'all grades' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:172154',
        parts: [
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:172155',
        parts: [
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:173372',
        parts: [
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'lean only' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'select' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    {
        id: 'fdc:173388',
        parts: [
            { attribute: 'bone', text: 'bone-in' },
            { attribute: 'formOrVariety', text: 'roast' },
            { attribute: 'fat', text: 'separable lean and fat' },
            { attribute: 'trim', text: 'lip-on' },
            { attribute: 'trim', text: '1/8-inch trim' },
            { attribute: 'grade', text: 'choice' },
            { attribute: 'cookingMethod', text: 'roasted' },
        ],
    },
    { id: 'fdc:2646172', parts: [{ attribute: 'grade', text: 'choice' }] },
];
